### ISSUE TITLE
Python import git module error for AWS Lambda

### ISSUE THREAD

**Issue by UdhavPawar** [lambci/git-lambda-layer#25] opened 2020-07-30 10:04 UTC
Hello, 

- I'm trying to `import git` in a python AWS lambda.
- After following through guide and adding a new layer with ARN: `arn:aws:lambda:us-east-1:553035198032:layer:git-lambda2:7` the function is not able to import module.
![image](https://user-images.githubusercontent.com/28740403/88910317-2e393700-d211-11ea-8dc8-08654891dee9.png)

- Verified the lambda's and layer's ARN match which is us-east-1.
- Error Response:

![image](https://user-images.githubusercontent.com/28740403/88910450-588af480-d211-11ea-86a1-024c1e2033c4.png)

Any guidance is appreciated. Thank You.

**Comment by mhart** [comment] 2020-07-30 12:03
This layer provides the `git` binary – not a Python module. This is a duplicate of https://github.com/lambci/git-lambda-layer/issues/15 – you can use the `subprocess` to call `git` binary from Python

**Closed by mhart** 2020-07-30 12:03 UTC
